# Generated by Django 6.0.2 on 2026-02-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='slug',
        ),
    ]
